//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Inputs/MarbleControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace CrazyMarble.Input
{
    public partial class @MarbleInputs : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @MarbleInputs()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""MarbleControls"",
    ""maps"": [
        {
            ""name"": ""Marble Controls"",
            ""id"": ""0fc6ad7d-b897-4e6c-b741-8fa12088c3ad"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""b269694c-9ff2-4d35-9541-25d1fb4addea"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Hop"",
                    ""type"": ""Button"",
                    ""id"": ""20091f4a-5f53-408b-9144-c47594d4acf1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Boost"",
                    ""type"": ""Button"",
                    ""id"": ""bb128415-4a3a-4b0d-b30a-f185f54fba15"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2418d268-c9e4-4d60-a1c0-28e94fae5fcb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1d98dd3c-0087-4371-ab9b-f8cae9e22402"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e2d04087-24e6-4051-838b-40e125b52ddc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8a610151-3569-4860-871c-d02578cc6046"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3b5e2e8b-a208-41f3-acab-3a134dc1d344"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""46106e98-a312-4494-8cdb-45f94ac5168e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""dbc38bfc-ccb4-4e7c-a3e9-d59bf226f28c"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a218a7cf-c853-47bd-bf35-fd6427678ee1"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7e857e24-42ee-4e8c-881d-4ed49c4f57bf"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""479e5a4d-a1c8-49c2-bd1e-f9bf30fbfd41"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e4f99b9a-3f6d-433a-b929-fa35adb0794e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Hop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eae46315-4c16-4434-9601-07ee979c975f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Hop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c25613c6-2aba-4d7a-9a8f-e4cca41250f7"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Hop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""715e3766-2ca9-4c94-9005-96833b30402d"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84804905-72dc-4bb5-9c11-c3115eece6ff"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Camera Controls"",
            ""id"": ""e5d57045-a368-4bc3-b31a-59b7c452a02d"",
            ""actions"": [
                {
                    ""name"": ""StartCameraRotation"",
                    ""type"": ""Button"",
                    ""id"": ""dafc83ac-4370-406f-9396-ed013679b90e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveCamera"",
                    ""type"": ""Value"",
                    ""id"": ""5bcb6bf7-2b10-4b24-8f99-2e2451898e34"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ZoomScroll"",
                    ""type"": ""Value"",
                    ""id"": ""bd2361b6-ee0f-4976-9501-66d7f9010e7a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ZoomIn"",
                    ""type"": ""Button"",
                    ""id"": ""169a2c73-2fe0-4f2a-a11c-b2c59c2fb38a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomOut"",
                    ""type"": ""Button"",
                    ""id"": ""18147983-8174-47c8-82d1-f242fa810417"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b3229350-a93f-48d9-9489-fa97e87cc5d0"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""StartCameraRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d94452ec-5b29-4902-ab1a-7305b62e61a8"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7ba740d-5ac3-4284-aa2e-859ace631dcf"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ZoomScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9ab8f2c-9927-4d85-95b2-4df268a21a30"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ZoomIn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cefa5deb-8ee5-44d9-b9e4-f951e0829da4"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ZoomOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Marble Controls
            m_MarbleControls = asset.FindActionMap("Marble Controls", throwIfNotFound: true);
            m_MarbleControls_Movement = m_MarbleControls.FindAction("Movement", throwIfNotFound: true);
            m_MarbleControls_Hop = m_MarbleControls.FindAction("Hop", throwIfNotFound: true);
            m_MarbleControls_Boost = m_MarbleControls.FindAction("Boost", throwIfNotFound: true);
            // Camera Controls
            m_CameraControls = asset.FindActionMap("Camera Controls", throwIfNotFound: true);
            m_CameraControls_StartCameraRotation = m_CameraControls.FindAction("StartCameraRotation", throwIfNotFound: true);
            m_CameraControls_MoveCamera = m_CameraControls.FindAction("MoveCamera", throwIfNotFound: true);
            m_CameraControls_ZoomScroll = m_CameraControls.FindAction("ZoomScroll", throwIfNotFound: true);
            m_CameraControls_ZoomIn = m_CameraControls.FindAction("ZoomIn", throwIfNotFound: true);
            m_CameraControls_ZoomOut = m_CameraControls.FindAction("ZoomOut", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Marble Controls
        private readonly InputActionMap m_MarbleControls;
        private IMarbleControlsActions m_MarbleControlsActionsCallbackInterface;
        private readonly InputAction m_MarbleControls_Movement;
        private readonly InputAction m_MarbleControls_Hop;
        private readonly InputAction m_MarbleControls_Boost;
        public struct MarbleControlsActions
        {
            private @MarbleInputs m_Wrapper;
            public MarbleControlsActions(@MarbleInputs wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_MarbleControls_Movement;
            public InputAction @Hop => m_Wrapper.m_MarbleControls_Hop;
            public InputAction @Boost => m_Wrapper.m_MarbleControls_Boost;
            public InputActionMap Get() { return m_Wrapper.m_MarbleControls; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MarbleControlsActions set) { return set.Get(); }
            public void SetCallbacks(IMarbleControlsActions instance)
            {
                if (m_Wrapper.m_MarbleControlsActionsCallbackInterface != null)
                {
                    @Movement.started -= m_Wrapper.m_MarbleControlsActionsCallbackInterface.OnMovement;
                    @Movement.performed -= m_Wrapper.m_MarbleControlsActionsCallbackInterface.OnMovement;
                    @Movement.canceled -= m_Wrapper.m_MarbleControlsActionsCallbackInterface.OnMovement;
                    @Hop.started -= m_Wrapper.m_MarbleControlsActionsCallbackInterface.OnHop;
                    @Hop.performed -= m_Wrapper.m_MarbleControlsActionsCallbackInterface.OnHop;
                    @Hop.canceled -= m_Wrapper.m_MarbleControlsActionsCallbackInterface.OnHop;
                    @Boost.started -= m_Wrapper.m_MarbleControlsActionsCallbackInterface.OnBoost;
                    @Boost.performed -= m_Wrapper.m_MarbleControlsActionsCallbackInterface.OnBoost;
                    @Boost.canceled -= m_Wrapper.m_MarbleControlsActionsCallbackInterface.OnBoost;
                }
                m_Wrapper.m_MarbleControlsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Movement.started += instance.OnMovement;
                    @Movement.performed += instance.OnMovement;
                    @Movement.canceled += instance.OnMovement;
                    @Hop.started += instance.OnHop;
                    @Hop.performed += instance.OnHop;
                    @Hop.canceled += instance.OnHop;
                    @Boost.started += instance.OnBoost;
                    @Boost.performed += instance.OnBoost;
                    @Boost.canceled += instance.OnBoost;
                }
            }
        }
        public MarbleControlsActions @MarbleControls => new MarbleControlsActions(this);

        // Camera Controls
        private readonly InputActionMap m_CameraControls;
        private ICameraControlsActions m_CameraControlsActionsCallbackInterface;
        private readonly InputAction m_CameraControls_StartCameraRotation;
        private readonly InputAction m_CameraControls_MoveCamera;
        private readonly InputAction m_CameraControls_ZoomScroll;
        private readonly InputAction m_CameraControls_ZoomIn;
        private readonly InputAction m_CameraControls_ZoomOut;
        public struct CameraControlsActions
        {
            private @MarbleInputs m_Wrapper;
            public CameraControlsActions(@MarbleInputs wrapper) { m_Wrapper = wrapper; }
            public InputAction @StartCameraRotation => m_Wrapper.m_CameraControls_StartCameraRotation;
            public InputAction @MoveCamera => m_Wrapper.m_CameraControls_MoveCamera;
            public InputAction @ZoomScroll => m_Wrapper.m_CameraControls_ZoomScroll;
            public InputAction @ZoomIn => m_Wrapper.m_CameraControls_ZoomIn;
            public InputAction @ZoomOut => m_Wrapper.m_CameraControls_ZoomOut;
            public InputActionMap Get() { return m_Wrapper.m_CameraControls; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CameraControlsActions set) { return set.Get(); }
            public void SetCallbacks(ICameraControlsActions instance)
            {
                if (m_Wrapper.m_CameraControlsActionsCallbackInterface != null)
                {
                    @StartCameraRotation.started -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnStartCameraRotation;
                    @StartCameraRotation.performed -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnStartCameraRotation;
                    @StartCameraRotation.canceled -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnStartCameraRotation;
                    @MoveCamera.started -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnMoveCamera;
                    @MoveCamera.performed -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnMoveCamera;
                    @MoveCamera.canceled -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnMoveCamera;
                    @ZoomScroll.started -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomScroll;
                    @ZoomScroll.performed -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomScroll;
                    @ZoomScroll.canceled -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomScroll;
                    @ZoomIn.started -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomIn;
                    @ZoomIn.performed -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomIn;
                    @ZoomIn.canceled -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomIn;
                    @ZoomOut.started -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomOut;
                    @ZoomOut.performed -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomOut;
                    @ZoomOut.canceled -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomOut;
                }
                m_Wrapper.m_CameraControlsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @StartCameraRotation.started += instance.OnStartCameraRotation;
                    @StartCameraRotation.performed += instance.OnStartCameraRotation;
                    @StartCameraRotation.canceled += instance.OnStartCameraRotation;
                    @MoveCamera.started += instance.OnMoveCamera;
                    @MoveCamera.performed += instance.OnMoveCamera;
                    @MoveCamera.canceled += instance.OnMoveCamera;
                    @ZoomScroll.started += instance.OnZoomScroll;
                    @ZoomScroll.performed += instance.OnZoomScroll;
                    @ZoomScroll.canceled += instance.OnZoomScroll;
                    @ZoomIn.started += instance.OnZoomIn;
                    @ZoomIn.performed += instance.OnZoomIn;
                    @ZoomIn.canceled += instance.OnZoomIn;
                    @ZoomOut.started += instance.OnZoomOut;
                    @ZoomOut.performed += instance.OnZoomOut;
                    @ZoomOut.canceled += instance.OnZoomOut;
                }
            }
        }
        public CameraControlsActions @CameraControls => new CameraControlsActions(this);
        private int m_KeyboardSchemeIndex = -1;
        public InputControlScheme KeyboardScheme
        {
            get
            {
                if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
                return asset.controlSchemes[m_KeyboardSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        public interface IMarbleControlsActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnHop(InputAction.CallbackContext context);
            void OnBoost(InputAction.CallbackContext context);
        }
        public interface ICameraControlsActions
        {
            void OnStartCameraRotation(InputAction.CallbackContext context);
            void OnMoveCamera(InputAction.CallbackContext context);
            void OnZoomScroll(InputAction.CallbackContext context);
            void OnZoomIn(InputAction.CallbackContext context);
            void OnZoomOut(InputAction.CallbackContext context);
        }
    }
}
